### ISSUE TITLE
compilation on OpenBSD 6.2 without thread support

### ISSUE THREAD

**Issue by wangp** [ivmai/bdwgc#198]
The GC does not compile on OpenBSD 6.2 with thread support disabled:

```
extra/../os_dep.c:1245:16: error: use of undeclared identifier 'USRSTACK'
      result = STACKBOTTOM;
               ^
./include/private/gcconfig.h:2406:38: note: expanded from macro 'STACKBOTTOM'
#         define STACKBOTTOM ((ptr_t)USRSTACK)
                                     ^
```

`USRSTACK` is defined in `<machine/vmparam.h>` but that is protected by `_KERNEL` in `<uvm/uvm_param.h>`:

```
#ifdef _KERNEL

#include <machine/vmparam.h>
```

`make check` passes using `HEURISTIC2` instead of `STACKBOTTOM` though.

**Comment by ivmai** [comment]
I will guard each STACKBOTTOM definition with "ifdef USRSTACK".

References:
* https://github.com/lattera/openbsd/blob/master/sys/arch/hppa64/include/vmparam.h

**Comment by ivmai** [comment]
Please test the above patch.

**Comment by wangp** [comment]
Thanks. We still need to define HEURISTIC2. HEURISTIC1 does not work. I only tested on x86_64.

**Comment by ivmai** [comment]
Fixed.
